# App name
spring.application.name=smart-campus-api

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://smartcampus:smart123@smart-campus-cluster.xxxxx.mongodb.net/smart_campus_db?retryWrites=true&w=majority

# Server port
server.port=8080

# JWT Secret (ඔයාගේ module ට ඕනේ)
jwt.secret=your-super-secret-key-change-this-in-production
jwt.expiration=86400000